# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json-schema', '~> 4.0'
gem 'rubocop', '~> 1.60'

group :test do
  gem 'minitest', '~> 5.20'
  gem 'mocha', '~> 2.1'
  gem 'rubocop-minitest', '~> 0.38.0'
end
